// src/pages/Quiz.svelte
<script lang="ts">
  import questionsData from "../data/questions";
  import Question from "../components/Question.svelte";
  import Results from "../components/Results.svelte";

  let currentQuestion = 0;
  let showResults = false;
  let answers: number[] = [];

  function handleQuestionConfirm(answerIndex: number) {
    answers[currentQuestion] = answerIndex;
    currentQuestion++;

    if (currentQuestion === questionsData.length) {
      showResults = true;
    }
  }

  function handleReset() {
    currentQuestion = 0;
    showResults = false;
    answers = [];
  }
</script>

<div class="quiz-container">
  <h1>Quiz</h1>
  {#if showResults}
    <Results
      questions={questionsData}
      answersIndexes={answers}
      on:reset={() => handleReset()}
    />
  {:else}
    <Question
      questions={questionsData}
      questionIndex={currentQuestion}
      on:confirm={(e) => handleQuestionConfirm(e.detail)}
    />
  {/if}
</div>

<style>
  .quiz-container {
    width: 100%;
    height: 100%;
    margin: 40px 78px;
  }

  .quiz-container > h1 {
    font-style: normal;
    font-weight: 400;
    font-size: 32px;
    line-height: 39px;
    margin-bottom: 10px;
  }
</style>

// src/pages/Quiz.vue
<script setup lang="ts">
  import { reactive, ref, computed } from 'vue';
  import Question from '../components/Question.vue';
  import Results from '../components/Results.vue';
  import questionsData from '../data/questions';

  const current = ref(0);

  const answers = reactive<number[]>([]);

  const showQuestions = computed(() => current.value < questionsData.length);

  function setAnswer(index: number) {
    answers.push(index);
    current.value++;
  }

  function reset() {
    answers.splice(0, answers.length);
    current.value = 0;
  }
</script>

<template>
  <div class="quiz-container">
    <h1>Quiz</h1>
    <Question
      v-if="showQuestions"
      :questions="questionsData"
      :currentIndex="current"
      @onSelect="setAnswer"
    />
    <Results v-else :questions="questionsData" :answersIndexes="answers" @onRestart="reset" />
  </div>
</template>

<style>
  .quiz-container {
    padding: 40px 78px;
  }

  .quiz-container > h1 {
    font-style: normal;
    font-weight: 400;
    font-size: 32px;
    line-height: 39px;
    margin-bottom: 10px;
  }
</style>
